part of parallel c++
SpiNNakerManchester/spinnaker_tools pull request #72
Opened 2018-03-23 13:07 UTC by alan-stokes

the current impression is that this improves the performance of data out. so pr-ed so that the rest of data out don't lose it.

2018-03-25 08:56 UTC, lplana commented
I'm afraid I don't that this should be merged as is.

1. Why bring in the 'mon_delegate' branch changes here? There is a separate pull request for that branch and this will just confuse issues.
2. I don't understand the changes to the 'setup' file. There is no indication as to why several lines were commented out.
3. I understand that the intention of the proposed modification is to leave the decision to throw away a mailbox message in the hands of the application code instead of the monitor. This relies on careful application coding, which is usually dangerous. The application can deadlock if it doesn't timeout or can run out of mailbox buffers if not paying attention.

2018-03-26 12:39 UTC, alan-stokes commented
hi luis. 

why 1. id guess that due to spinnman being tied to it, then new changes for the tools can be based off it, this doesn't mean this has to be merged before mon deligate has already been done. ill add the dependency for clarity. (plus i didn't know where it sat, just that it was needed for the speed up).

2 & 3 i guess @lucaperes could explain, as i'm not taking ownership of this PR, just putting it into the space of the Data out project so that its changes are not lost, if indeed they are needed at all is a separate discussion that im not putting a hand in.

2018-03-26 12:46 UTC, rowleya commented
I think these changes were experimental - more work should be done to avoid the issues raised.

2018-03-26 12:53 UTC, rowleya commented on scamp/scamp-isr.c
>  	    sw_error(SW_OPT);
A possible simple option is to add a vcpu->mbox_mp_cmd = SHM_ERR here, which will then tell the sender that something has changed at least.

2018-03-26 13:09 UTC, lucaperes commented
> I think these changes were experimental
I confirm that

2018-03-27 14:50 UTC, dkfellows requested changes
Just one comment here; it looks like something done to a bit of (non-obvious) setup code was actually wrong.

I'd be totally for someone providing better options for the setup code too in the non-GCC case.

2018-03-27 14:50 UTC, dkfellows commented on setup
> +#fi
Why are these three lines commented out?

2018-03-27 14:50 UTC, dkfellows commented on setup
> +#fi
The protection against being run as a stand-alone script (which won't work; it's a script whose purpose is to set environment variables for other scripts) is highly valuable. I see no good reason to remove it.

2018-04-06 13:22 UTC, alan-stokes commented
killing as the correct thing is here https://github.com/SpiNNakerManchester/spinnaker_tools/pull/73

2018-04-06 13:22 UTC, closed without merging